//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behold_Emailer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tableau_server {
            get {
                return ((string)(this["tableau_server"]));
            }
            set {
                this["tableau_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string server_admin_username {
            get {
                return ((string)(this["server_admin_username"]));
            }
            set {
                this["server_admin_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string server_admin_password {
            get {
                return ((string)(this["server_admin_password"]));
            }
            set {
                this["server_admin_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string repository_user {
            get {
                return ((string)(this["repository_user"]));
            }
            set {
                this["repository_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string repository_pw {
            get {
                return ((string)(this["repository_pw"]));
            }
            set {
                this["repository_pw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_server {
            get {
                return ((string)(this["smtp_server"]));
            }
            set {
                this["smtp_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string text_email_template_filename {
            get {
                return ((string)(this["text_email_template_filename"]));
            }
            set {
                this["text_email_template_filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string email_sender {
            get {
                return ((string)(this["email_sender"]));
            }
            set {
                this["email_sender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tabcmd_program_location {
            get {
                return ((string)(this["tabcmd_program_location"]));
            }
            set {
                this["tabcmd_program_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tabcmd_config_location {
            get {
                return ((string)(this["tabcmd_config_location"]));
            }
            set {
                this["tabcmd_config_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string html_email_template_filename {
            get {
                return ((string)(this["html_email_template_filename"]));
            }
            set {
                this["html_email_template_filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string email_subject {
            get {
                return ((string)(this["email_subject"]));
            }
            set {
                this["email_subject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection selected_schedule_names {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["selected_schedule_names"]));
            }
            set {
                this["selected_schedule_names"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string export_archive_folder {
            get {
                return ((string)(this["export_archive_folder"]));
            }
            set {
                this["export_archive_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Behold_Emailer.SerializableStringDictionary topLeft {
            get {
                return ((global::Behold_Emailer.SerializableStringDictionary)(this["topLeft"]));
            }
            set {
                this["topLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Behold_Emailer.SerializableStringDictionary topCenter {
            get {
                return ((global::Behold_Emailer.SerializableStringDictionary)(this["topCenter"]));
            }
            set {
                this["topCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Behold_Emailer.SerializableStringDictionary topRight {
            get {
                return ((global::Behold_Emailer.SerializableStringDictionary)(this["topRight"]));
            }
            set {
                this["topRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Behold_Emailer.SerializableStringDictionary bottomLeft {
            get {
                return ((global::Behold_Emailer.SerializableStringDictionary)(this["bottomLeft"]));
            }
            set {
                this["bottomLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Behold_Emailer.SerializableStringDictionary bottomCenter {
            get {
                return ((global::Behold_Emailer.SerializableStringDictionary)(this["bottomCenter"]));
            }
            set {
                this["bottomCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Behold_Emailer.SerializableStringDictionary bottomRight {
            get {
                return ((global::Behold_Emailer.SerializableStringDictionary)(this["bottomRight"]));
            }
            set {
                this["bottomRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_server_username {
            get {
                return ((string)(this["smtp_server_username"]));
            }
            set {
                this["smtp_server_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_server_password {
            get {
                return ((string)(this["smtp_server_password"]));
            }
            set {
                this["smtp_server_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_server_tls {
            get {
                return ((string)(this["smtp_server_tls"]));
            }
            set {
                this["smtp_server_tls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_server_port {
            get {
                return ((string)(this["smtp_server_port"]));
            }
            set {
                this["smtp_server_port"] = value;
            }
        }
    }
}
